### ISSUE TITLE
Social Media: requests to share postings

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/administrative#27]
Here, please include what you would like to share. If you have suggested text, feel free to include as well.

@laurburke

### Example
- [ ] share some of Julien's blog posts:
  - [ ] [Pairwise Distances Reductions](https://jjerphan.xyz/pairwise-distances-reductions.html)
- [ ] share video presentation by: xxx
- [ ] xxx

**Comment by laurburke** [comment]
@reshamas Do we want to close this and open a new issue in the Communication repo?

**Comment by reshamas** [comment]
@laurburke 
Yes.  Opened issue here:  https://github.com/scikit-learn/communication/issues/1

Closing this one.
